"""
gecsg.builder.simple_builder
=============================
SimpleGECSGBuilder: a fluent builder for GECSGGrammar.

Design pattern: Builder
-----------------------
The builder hides the low-level coset indices and group manipulation,
letting you specify grammars in a readable DSL:

    g = (SimpleGECSGBuilder("Gene", group=dna_default_group(), k=3)
         .rule("Gene",  ["CDS"])
         .rule("CDS",   ["Codon"])
         .rule("CDS",   ["Codon", "CDS"])
         .break_coset(0, "ATG")    # coset 0 -> "ATG"
         .break_coset(1, "TAA")
         .build())

Coset resolution
----------------
The builder accepts coset specifications as:
  int             -> coset index in G/G_i
  str "Ci"        -> coset by label (e.g. "C0", "C1")
  Coset object    -> used directly

Breaking rules can be specified by coset or by raw string
(the builder finds the coset whose orbit contains the string).

Pre-defined grammars
--------------------
  SimpleGECSGBuilder.dna_codon_grammar()  -> standard DNA codon grammar
  SimpleGECSGBuilder.palindrome_grammar() -> stem-loop palindrome grammar
  SimpleGECSGBuilder.abstract_z2_grammar() -> toy Z2 grammar for testing
"""

from __future__ import annotations
from typing import List, Optional, Union, Tuple, Dict

from gecsg.core.group import Group
from gecsg.core.coset import Coset, CosetSpace
from gecsg.core.dna_groups import (
    dna_default_group, Z2ComplementGroup,
    DirectProductGroup, Z2ReversalGroup, Z3CyclicGroup
)
from gecsg.grammar.grammar import GECSGGrammar
from gecsg.grammar.symbols import NonTerminal
from gecsg.grammar.rule import SFElement


CosetSpec = Union[int, str, Coset]


class SimpleGECSGBuilder:
    """
    Fluent builder for GECSGGrammar.

    Parameters
    ----------
    start   : name of the start symbol
    group   : ambient group G (default: dna_default_group(), order 12)
    subgroup_indices : indices of G_i ⊆ G (default: auto from k)
    k       : breaking granularity; default 3 (codon level)
    """

    def __init__(
        self,
        start:             str   = "S",
        group:             Optional[Group] = None,
        subgroup_indices:  Optional[List[int]] = None,
        k:                 int   = 3,
    ):
        self._start = start
        self._k     = k
        self._G     = group or dna_default_group()

        # Default subgroup: if not given, use the smallest subgroup
        # that gives |G/G_i| == 4  (natural DNA alphabet size)
        if subgroup_indices is None:
            self._H_idx = self._default_subgroup()
        else:
            self._H_idx = subgroup_indices

        # Pending rules (added before build())
        self._gen_rules: List[Dict] = []
        self._brk_rules: List[Dict] = []

    # ── Subgroup default ──────────────────────────────────────────────────────

    def _default_subgroup(self) -> List[int]:
        """
        Find a subgroup G_i such that |G/G_i| == 4
        (gives a 4-letter alphabet, natural for DNA).
        If none found, use trivial subgroup {e}.
        """
        G = self._G
        target_size = G.order // 4
        if target_size < 1:
            return [0]
        # Try to find a subgroup of size target_size
        # For DirectProductGroup(Z2 x Z2, Z3): Z3 is the natural G_i
        # We look for the Z3-like subgroup: elements that form a cyclic
        # subgroup of order target_size
        for i in range(1, G.order):
            # Try cyclic subgroup generated by element i
            subgrp = [0]
            curr = i
            while curr not in subgrp:
                subgrp.append(curr)
                curr = G.multiply(curr, i)
            if len(subgrp) == target_size and G.is_subgroup(subgrp):
                return subgrp
        return [0]   # fallback: trivial subgroup

    # ── Coset resolution ──────────────────────────────────────────────────────

    def _build_temp_grammar(self) -> GECSGGrammar:
        """Build the grammar with current rules."""
        g = GECSGGrammar(
            group=self._G,
            subgroup_indices=self._H_idx,
            start=self._start,
            k=self._k,
        )
        # Register all nonterminals first
        for r in self._gen_rules:
            g.NT(r["lhs"])
            for sym in r.get("rhs", []):
                if isinstance(sym, str):
                    g.NT(sym)
        # Add generation rules
        for r in self._gen_rules:
            g.add_generation_rule(
                lhs=r["lhs"],
                rhs=r["rhs"],
                left_ctx=r.get("left_ctx"),
                right_ctx=r.get("right_ctx"),
                weight=r.get("weight", 1.0),
            )
        # Add breaking rules
        for br in self._brk_rules:
            g.add_breaking_rule(
                coset=br["coset"],
                string=br["string"],
                prob=br.get("prob", 1.0),
            )
        return g

    # ── Fluent API ────────────────────────────────────────────────────────────

    def rule(
        self,
        lhs:       str,
        rhs:       List[str],
        left_ctx:  Optional[List[str]] = None,
        right_ctx: Optional[List[str]] = None,
        weight:    float = 1.0,
    ) -> "SimpleGECSGBuilder":
        """
        Add a generation rule orbit representative.

        lhs / rhs elements are strings:
          - strings that look like nonterminals are treated as NT
          - explicit coset references not needed here; use break_*
        """
        self._gen_rules.append({
            "lhs": lhs, "rhs": rhs,
            "left_ctx": left_ctx, "right_ctx": right_ctx,
            "weight": weight,
        })
        return self

    def break_coset(
        self,
        coset_idx: int,
        string:    str | Tuple[str, ...],
        prob:      float = 1.0,
    ) -> "SimpleGECSGBuilder":
        """
        Add a breaking rule: coset[coset_idx] →₂ string.

        Example:
            .break_coset(0, "ATG")  # coset 0 maps to ATG
        """
        s = tuple(string) if isinstance(string, str) else string
        self._brk_rules.append({"coset": coset_idx, "string": s, "prob": prob})
        return self

    def break_all_cosets(
        self,
        coset_to_string: Dict[int, str],
    ) -> "SimpleGECSGBuilder":
        """
        Add multiple breaking rules from a dict {coset_idx: raw_string}.

        Example:
            .break_all_cosets({0: "ATG", 1: "TAC", 2: "TAA", 3: "ATT"})
        """
        for coset_idx, string in coset_to_string.items():
            self.break_coset(coset_idx, string)
        return self

    def auto_break_from_alphabet(
        self,
        alphabet: List[str],
        k:        Optional[int] = None,
    ) -> "SimpleGECSGBuilder":
        """
        Automatically generate breaking rules by computing orbits.

        For each orbit in Σ_raw^k / G, assigns one representative
        coset to each orbit representative string.

        Parameters
        ----------
        alphabet : raw symbol alphabet (e.g. ["A","T","G","C"])
        k        : breaking granularity (default: self._k)
        """
        from itertools import product as iproduct

        k = k or self._k
        G = self._G
        H_idx = self._H_idx

        # Build a temporary grammar to access the coset space
        temp = GECSGGrammar(
            group=G, subgroup_indices=H_idx,
            start=self._start, k=k
        )
        CS = temp.coset_space

        # Enumerate all strings of length k
        all_strings = [tuple(s) for s in iproduct(alphabet, repeat=k)]

        # For each string, find its orbit representative
        visited: set = set()
        coset_idx = 0

        for s in all_strings:
            if s in visited:
                continue
            # Compute the orbit of s under G (using act_on_sequence)
            orbit = set()
            for g in G.elements:
                orbit.add(tuple(G.act_on_sequence(g.index, list(s))))

            # Assign coset 0..n-1 to this orbit's representative
            rep = min(orbit)   # lexicographic representative
            # Find a coset in CS that can map to this orbit
            # We use the coset whose representative group element maps identity -> s
            # Simple assignment: just use the orbit index as coset index
            if coset_idx < CS.size:
                self.break_coset(coset_idx, rep)
                coset_idx += 1

            visited.update(orbit)

        return self

    def build(self, freeze: bool = True) -> GECSGGrammar:
        """
        Construct and return the GECSGGrammar.

        Parameters
        ----------
        freeze : if True, freeze the grammar after building.
        """
        g = self._build_temp_grammar()
        if freeze:
            g.freeze()
        return g

    def describe_coset_space(self) -> None:
        """Print the coset space structure before building."""
        CS = self._G.coset_space(self._H_idx)
        CS.describe()

    # ─────────────────────────────────────────────────────────────────────────
    # Pre-defined grammars
    # ─────────────────────────────────────────────────────────────────────────

    @staticmethod
    def dna_codon_grammar(
        group: Optional[Group] = None,
    ) -> GECSGGrammar:
        """
        Standard DNA codon grammar (k=3, G=Z2×Z2×Z3, order 12).

        Language: valid codon sequences (Gene → CDS → Codon*)
        Coset structure: 4 cosets of Z3 in G, one per nucleotide class.
        Breaking rules: one representative codon per coset orbit.
        """
        G = group or dna_default_group()
        H_idx = SimpleGECSGBuilder._z3_subgroup(G)

        b = (SimpleGECSGBuilder(start="Gene", group=G,
                                subgroup_indices=H_idx, k=3)
             # Structural rules (no cosets in RHS)
             .rule("Gene",  ["CDS"])
             .rule("CDS",   ["Codon"])
             .rule("CDS",   ["Codon", "CDS"])
        )

        # Add breaking rules: one representative per coset orbit
        # Coset 0 -> ATG (start/Met class)
        # Coset 1 -> TAA (stop class)
        # Coset 2 -> GCT (Ala class)
        # Coset 3 -> GGT (Gly class)
        b.break_coset(0, "ATG")
        b.break_coset(1, "TAA")
        b.break_coset(2, "GCT")
        b.break_coset(3, "GGT")

        return b.build()

    @staticmethod
    def palindrome_grammar(
        group: Optional[Group] = None,
    ) -> GECSGGrammar:
        """
        DNA palindrome / stem-loop grammar (k=1, Z2 complement).

        Language: palindromic sequences where A pairs with T, G with C.
        Stem → [A] Stem [T]  |  [G] Stem [C]  |  Loop
        Loop → [A] | [G]
        """
        G = group or Z2ComplementGroup()
        H_idx = [0]   # trivial subgroup: |G/G_i| = 2

        b = (SimpleGECSGBuilder(start="Stem", group=G,
                                subgroup_indices=H_idx, k=1)
             .rule("Stem", ["Stem"])  # placeholder; real rules use cosets
             .rule("Stem", ["Loop"])
             .rule("Loop", [])        # epsilon production
        )
        # Breaking: coset 0 = {e} -> A,G (symmetric),
        #           coset 1 = {c} -> T,C (anti-symmetric)
        b.break_coset(0, "A")
        b.break_coset(0, "G")
        b.break_coset(1, "T")
        b.break_coset(1, "C")
        return b.build()

    @staticmethod
    def abstract_z2_grammar() -> GECSGGrammar:
        """
        Toy Z2 grammar over {a,b} with swap a↔b.
        Useful for unit testing the parser.

          S → A B
          A → [a]   (coset 0 → "a", or by symmetry → "b")
          B → [a][a] or [b][b]
        """
        from gecsg.core.dna_groups import Z2ComplementGroup

        class Z2AbsGroup(Z2ComplementGroup):
            _COMP = {"a": "b", "b": "a"}
            def __init__(self):
                super().__init__()
                self._name = "Z2_abstract"

        G = Z2AbsGroup()
        H_idx = [0]   # trivial: |G/G_i| = 2

        b = (SimpleGECSGBuilder(start="S", group=G,
                                subgroup_indices=H_idx, k=1)
             .rule("S", ["A", "B"])
             .rule("A", ["A"])   # A produces one symbol
             .rule("B", ["A", "A"])   # B produces two symbols
             .break_coset(0, "a")    # coset 0 -> "a"  (orbit: {a,b})
        )
        return b.build()

    @staticmethod
    def _z3_subgroup(G: Group) -> List[int]:
        """
        Find a subgroup of order |G|/4 in G (for 4-letter alphabet).
        Defaults to trivial if none found.
        """
        target = G.order // 4
        if target <= 0:
            return [0]
        for start_idx in range(1, G.order):
            subgrp = [0]
            curr = start_idx
            while curr not in subgrp:
                subgrp.append(curr)
                curr = G.multiply(curr, start_idx)
            if len(subgrp) == target and G.is_subgroup(subgrp):
                return subgrp
        return [0]

    def __repr__(self) -> str:
        return (f"SimpleGECSGBuilder(start='{self._start}', "
                f"G={self._G.name}, k={self._k}, "
                f"rules={len(self._gen_rules)}, "
                f"breaking={len(self._brk_rules)})")
